package com.lanou.chenfengyao.databasedemo.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEST_BEAN".
 */
public class TestBean {

    private Long id;
    /** Not-null value. */
    private String name;
    private Integer score;
    private java.util.Date date;

    public TestBean() {
    }

    public TestBean(Long id) {
        this.id = id;
    }

    public TestBean(Long id, String name, Integer score, java.util.Date date) {
        this.id = id;
        this.name = name;
        this.score = score;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
