package com.lanou3g.greendaodemo.entity.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lanou3g.greendaodemo.entity.greendao.PersonEntity;

import com.lanou3g.greendaodemo.entity.greendao.PersonEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personEntityDaoConfig;

    private final PersonEntityDao personEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personEntityDaoConfig = daoConfigMap.get(PersonEntityDao.class).clone();
        personEntityDaoConfig.initIdentityScope(type);

        personEntityDao = new PersonEntityDao(personEntityDaoConfig, this);

        registerDao(PersonEntity.class, personEntityDao);
    }
    
    public void clear() {
        personEntityDaoConfig.getIdentityScope().clear();
    }

    public PersonEntityDao getPersonEntityDao() {
        return personEntityDao;
    }

}
